### ISSUE TITLE
This doesn't work how it should work

### ISSUE THREAD

**Issue by TJHUNTER2001** [Nurrl/Duckuino#25]
I try to open notepad and write some stuff in it but it doesn't work.
Here is the script:

> DELAY 5000
> GUI r
> DELAY 5000
> 
> STRING notepad
> ENTER
> DELAY 5000
> 
> STRING Hello
> DELAY 5000
> ENTER
> DELAY 5000
> ENTER
> DELAY 5000
> STRING Why did you plug this in?

**Comment by Nurrl** [comment]
@TJHUNTER2001, this is not a compiler issue while the code compiles..

Are you using an English mapping, and did you used the download button or copy/paste ?
_It doesn't work_ is not really verbose, can you explain ?

**Comment by TJHUNTER2001** [comment]
Well, I think I found the problem.
It sends all the keys as a QWERTY keyboard were it should be sent as AZERTY.

For example:
"My name is TJ" becomes "Öz nqöe is TJ"

**Comment by TJHUNTER2001** [comment]
Note: it isn't QWERTY, it is QWERTZ

**Comment by TJHUNTER2001** [comment]
One solution I found is to press ALT+SHIFT and then write the strings.

Then the code would look like this:

> DELAY 5000
> GUI r
> DELAY 5000
> 
> STRING notepqd
> DELAY 5000
> ENTER
> DELAY 5000
> 
> STRING Hello
> DELAY 5000
> ENTER
> DELAY 5000
> ENTER
> DELAY 5000
> STRING Yhz did zou plug this inM

**Comment by TJHUNTER2001** [comment]
This is another solution I came up with:

> DELAY 5000
> GUI r
> DELAY 5000
> 
> STRING notepqd
> DELAY 100
> ENTER
> DELAY 2000
> 
> ALT SHIFT
> ALT SHIFT
> DELAY 100
> STRING Hello
> DELAY 100
> ENTER
> DELAY 50
> ENTER
> DELAY 50
> STRING Why did you plug this in?
> ALT SHIFT

**Comment by TJHUNTER2001** [comment]
I still need some help with this, could anyone give a solution or tell me were to ask pls.

**Comment by Plazmaz** [comment]
Please provide the following information to help us address the problem more easily:
The original duckyscript code
The Arduino output or the generated Arduino project
Your keyboard layout/language
The full output of the script
The expected output

**Comment by TJHUNTER2001** [comment]
- [x ] The original duckyscript code : Already posted
- [x ] The Arduino output or the generated Arduino project : See video
- [x ] Your keyboard layout/language : AZERTY (Dutch if it mathers)
- [x ] The full output of the script : See video
- [x ] The expected output : See video

PS: videos'll come later

**Comment by TJHUNTER2001** [comment]
Output original code:

> /*
>  * Generated with <3 by Dckuino.js, an open source project !
>  */
> 
> #include "Keyboard.h"
> 
> void typeKey(int key)
> {
>   Keyboard.press(key);
>   delay(50);
>   Keyboard.release(key);
> }
> 
> /* Init function */
> void setup()
> {
>   // Begining the Keyboard stream
>   Keyboard.begin();
> 
>   // Wait 500ms
>   delay(500);
> 
>   delay(5000);
> 
>   Keyboard.press(KEY_LEFT_GUI);
>   Keyboard.press('r');
>   Keyboard.releaseAll();
> 
>   delay(5000);
> 
>   Keyboard.print("notepad");
> 
>   typeKey(KEY_RETURN);
> 
>   delay(5000);
> 
>   Keyboard.print("Hello");
> 
>   delay(5000);
> 
>   typeKey(KEY_RETURN);
> 
>   delay(5000);
> 
>   typeKey(KEY_RETURN);
> 
>   delay(5000);
> 
>   Keyboard.print("Why did you plug this in?");
> 
>   // Ending stream
>   Keyboard.end();
> }
> 
> /* Unused endless loop */
> void loop() {}

**Comment by TJHUNTER2001** [comment]
Download file (.avi format) at:
https://drive.google.com/open?id=0By4Bw1LyCjW1MzM0MFpoVTdJanc

**Comment by Plazmaz** [comment]
Try using the "Download Sketch" function instead of copying+pasting the code.

**Comment by TJHUNTER2001** [comment]
Same result :(

**Comment by Nurrl** [comment]
By selecting the good locale.... @TJHUNTER2001

**Comment by TJHUNTER2001** [comment]
What do you mean with good locale?

**Comment by Nurrl** [comment]
I mean an AZERTY locale like **fr_FR** :D

**Comment by TJHUNTER2001** [comment]
Sorry, feel me like a noob but how do I do that?

**Comment by Nurrl** [comment]
Click the **Download Sketch** button, then select the locale and click **Download** :D

**Comment by TJHUNTER2001** [comment]
Didn't help :'(

**Comment by Andsoeg** [comment]
This line;  Keyboard.print("cd \"%USERPROFILE%\\Desktop\" & for /f \"tokens=2 delims=:\" %A in ('netsh wlan show interface ^| findstr \"SSID\" ^| findstr /v \"BSSID\"') do set A=%A");

Turned out like this in console;

cd Æ%USERPROFILE%'DesktopÆ / for -f Ætokens\2 delims\ØÆ %A in )ænetsh wlan show interface &* findstr ÆSSIDÆ &* findstr -v ÆBSSIDÆæ= do set A\%A

Does the rubber ducky (arduino) use the system language keyboard? Very strange. If i plug a regular keyboard into my pc, that keyboard uses a standalone language.

**Comment by Nurrl** [comment]
@Andsoeg On Windows you could add an <code>ALT SPACE</code> before the code...

**Comment by TJHUNTER2001** [comment]
Alt space? Why?

**Comment by Nurrl** [comment]
No, forget this, ALT SPACE is to swap locales on Windows, but you need to have the english one activated .-. Worst idea I ever talked about x)

**Comment by TJHUNTER2001** [comment]
Windows lang (unknown) on testing sub it's Dutch.

**Comment by exzotic** [comment]
help i have done these steps used the download and tried the french locale on the downloader still having problems

**Comment by Nurrl** [comment]
Hi @exzotic, what did you done ?

**Comment by Nurrl** [comment]
Hi @TJHUNTER2001, @Andsoeg and @exzotic, the **v2.0-pre** has been released, can you try again to compile the code and send it to your Arduino ?
