### ISSUE TITLE
Lay out goals and thoughts for v2.0

### ISSUE THREAD

**Issue by Plazmaz** [Nurrl/Duckuino#26]
I suggest laying out your thoughts and opening discussion for the v2.0 you've mentioned via an issue, and creating a milestone with the results.

**Comment by Nurrl** [comment]
Yep, (I'm sorry, I really didn't saw this !), I managed to get a working Dckuino.js version with modules, I also recreated the GUI, so it's more user-friendly :D I need to fix some bugs and issues, but I think I'll release it soon ;D
Also, I'm very unfamiliar with Milestone, would you like to be added as contributor, so you can create it ? @Plazmaz

**Comment by Plazmaz** [comment]
I mentioned it in a comment on the last issue, but is there some way we could get in contact via email or private message of some sort?

**Comment by Plazmaz** [comment]
Your previous email doesn't seem to work

**Comment by Nurrl** [comment]
Oh, whoops, I changed it :3 Go hack.chat ?

**Comment by Nurrl** [comment]
https://hack.chat/?dckuino
