### ISSUE TITLE
Ram optimization

### ISSUE THREAD

**Issue by Flambello** [Nurrl/Duckuino#28]
hello
instead of Keyboard.print("hello world");
 can you make it do Keyboard.print(F("hello world));
so that the print will not get stored in the ram and instead go in the flash memory making longer line scripts possible

the foto is of a verry long script 
without the (F()) it uses around 8k ram
with the (F()) it uses only 220 

![untitled](https://cloud.githubusercontent.com/assets/28274575/25771706/7ed9bb24-3261-11e7-98d9-5884cab0183b.png)

**Comment by Plazmaz** [comment]
This is something I used in the original version of Duckuino, but it seems to have gotten lost in translation. However, writing everything to flash may not be the best way of doing things, otherwise, it would probably be the default, I'll need to look into this more

**Comment by Flambello** [comment]
Oooh ok thnx for the responce

**Comment by Nurrl** [comment]
@Plazmaz You could add it in your post-processor :D Or we could add a checkbox to let the user decide ^^

**Comment by Flambello** [comment]
Uuuu that whould be nice!

**Comment by Plazmaz** [comment]
I think that sounds good. I like the idea of being able to disable it.

**Comment by Flambello** [comment]
Haha best software on github!

**Comment by Plazmaz** [comment]
@Flambello if you think it's good now, get ready for v2.

**Comment by Flambello** [comment]
No problem im glad my suggestion helps!!!

**Comment by bytedeez** [comment]
@Flambello @Plazmaz 
I have about 5 scripts i need to use this for. I am still learning .js and jquery at the moment
Where in the code could i make this change temporarily? 
I searched through the code but nothing stuck out to a novice like myself to make this change without some expert advice,
Thanks in advance!

**Comment by Plazmaz** [comment]
@bytedeez consider it done.

**Comment by Nurrl** [comment]
Since v2 is here and this disappeared, I'm reopening this, @Plazmaz should release the Ram Optimization update some days :D

**Comment by Plazmaz** [comment]
@Nurrl nope, this is something different. This issue is asking for the use of Fstrings instead of normal strings. Should be an easy fix 😄

**Comment by Nurrl** [comment]
Yep ^^ But it Optimizes ram x)
