### ISSUE TITLE
No DEFAULT_DELAY

### ISSUE THREAD

**Issue by keeganjk** [Nurrl/Duckuino#29]
When you try to use `DEFAULT_DELAY` or `DEFAULTDELAY` to set a default delay between each command, it results in the error, `An error occured, the compiler returned undefined content`.

According to the USB Rubber Ducky Wiki, 

> # DEFAULT_DELAY or DEFAULTDELAY
> 
> DEFAULT_DELAY or DEFAULTDELAY is used to define how long (milliseconds) to wait between each subsequent command. DEFAULT_DELAY must be issued at the beginning of the ducky script and is optional. Not specifying the DEFAULT_DELAY will result in faster execution of ducky scripts. This command is mostly useful when debugging.
> 
> Command	Parameters
> DEFAULT_DELAY	0..->
> DEFAULTDELAY	0..->
> <pre>DEFAULT_DELAY 100
> REM delays 100ms between each subsequent command sequence</pre>

`DEFAULT_DELAY` simply sets a default delay time between each command.

**Comment by Nurrl** [comment]
Hi, @keeganjk thanks for reporting this error, but we need more informations please :)
Please provide us : 
  - The uncompiled script
  - What the compiler says (On the bottom of the page, the long bar ;D), this should help us to solve your problem..

**Comment by Plazmaz** [comment]
@Nurrl I just think we haven't implemented this command. I remember noticing this at one point.

**Comment by Nurrl** [comment]
@Plazmaz [Dckuino.js Line 233](https://github.com/Nurrl/Duckuino/blob/master/Dckuino.js#L233) I implemented it when I added the REPEAT command :)

**Comment by keeganjk** [comment]
I've updated my comment, I've added some info.

**Comment by Nurrl** [comment]
I know, but when I use it, it works... @keeganjk

**Comment by Nurrl** [comment]
![screenshot from 2017-06-04 10-36-20](https://cloud.githubusercontent.com/assets/15341887/26760157/00a84df2-4912-11e7-9682-8e23b554fe9d.png)

**Comment by keeganjk** [comment]
@Nurrl Not for me... 
![screen shot 2017-06-04 at 19 26 28](https://cloud.githubusercontent.com/assets/24554125/26766257/c8a3fc22-495b-11e7-8ad6-c236be00d2f8.png)

**Comment by Plazmaz** [comment]
@keeganjk please ensure you are running the code yourself, versus using someone else's hosted version. We've had issues with version conflicts in hosted versions of the project

**Comment by keeganjk** [comment]
@Plazmaz I just downloaded it to see if the latest version worked. It didn't work.

**Comment by Plazmaz** [comment]
@keeganjk I am able to reproduce with just one line, but when there's other data in the editor, it does not occur

**Comment by keeganjk** [comment]
@Plazmaz @Nurrl I've found the problem! It requires multiple lines and some hosted versions are outdated.

**Comment by Plazmaz** [comment]
@Nurrl perhaps we should give a better error for this.
