### ISSUE TITLE
Language error

### ISSUE THREAD

**Issue by loidor** [Nurrl/Duckuino#30]
When I'm plugging in my arduino on an English computer everything works flawlessly, but when plugging it in on a Swedish one everything ends up wonky. / is for example replaced by -. 

This is due to keyboard layout (Swedish keyboards does indeed have - where English ones have /). Would it be possible to force the script to adapt to the current keyboard layout?

**Comment by Nurrl** [comment]
Hi @loidor, this project includes **LocaleKeyboard.js**, which is an other project, and fixes this bug, but there is currently no Swedish locale.

**Comment by loidor** [comment]
Lovely, then there's a way to solve it :) I'll look into generating a Swedish contribution to **LocaleKeyboard.js**. I close this since it's kind of solved.
