### ISSUE TITLE
Problems when sending code to Arduino

### ISSUE THREAD

**Issue by FCucumberGames** [Nurrl/Duckuino#36]
![image](https://user-images.githubusercontent.com/32435964/31056975-d67e5dde-a6fc-11e7-9e20-d3275725abd5.png)
How does it works??

**Comment by Nurrl** [comment]
Maybe try to set your Board to **Arduino Mini** ?

**Comment by FCucumberGames** [comment]
Thanks, I would try

**Comment by FCucumberGames** [comment]
![image](https://user-images.githubusercontent.com/32435964/31136736-d469e614-a88a-11e7-88cd-ed728e38cf72.png)
OOPS, it doesn't work

**Comment by Nurrl** [comment]
Have you updated to the latest Arduino IDE version ? @FCucumberGames

**Comment by FCucumberGames** [comment]
Shit, I'm fucking retard. I use Arduino Nano

**Comment by Nurrl** [comment]
**Arduino Nano** should work tho..

**Comment by FCucumberGames** [comment]
Hmm, so, I don't know why I cannot complie this code

**Comment by FCucumberGames** [comment]
It's 1.8.4 arduino IDE version

**Comment by Nurrl** [comment]
There is the 1.8.5 update, but I don't thinks that's the problem..
I also noticed that the first line chnaged betwin your two screenshots: 
`#include <Keyboard.h>` to `#include ""Keyboard.h"`, maybe that could be the problem..

**Comment by FCucumberGames** [comment]
I have tried all variants of this line like "Keyboard.h", <Keyboard.h>, 'Keyboard.h'

**Comment by FCucumberGames** [comment]
Thank you for help, but I have burned my arduino while I was brazing a button to it(((

**Comment by Plazmaz** [comment]
@FCucumberGames  D: Oh noes!
https://github.com/Nurrl/Duckuino/issues/12#issuecomment-261359817 temporary workaround(too late sadly)

**Comment by Plazmaz** [comment]
@Nurrl we should find a more permanent fix. Also, go ahead and push v2 if you think it's ready. I'll worry about the code optimizer later.

**Comment by Nurrl** [comment]
@Plazmaz The problem is that v2 isn't ready, I didn't made the support for DEFAULTDELAY..

**Comment by Nurrl** [comment]
And we need to figure out how to load modules without *evil*(**eval()**) also..

**Comment by Nurrl** [comment]
Hi @FCucumberGames, the **v2.0-pre** has been released, can you try to compile your code again ?

**Comment by FCucumberGames** [comment]
No, it still doesn't work. It's the same problem

**Comment by Nurrl** [comment]
@FCucumberGames If you still have the problem, I'll reopen this.
