### ISSUE TITLE
"7" instead of "r"

### ISSUE THREAD

**Issue by hyWse** [Nurrl/Duckuino#42]
__Input code:__
```vb
GUI r
```
__Output code:__
```arduino
 Keyboard.press(KEY_LEFT_GUI);
 Keyboard.press("r");
 Keyboard.releaseAll();
```

Hi, when I compile this code, Windows runs GUI + 7 instead of GUI + r. (I have selected the correct keyboard)

**Comment by Nurrl** [comment]
Hi @hyWse, that's interesting, what is your keyboard locale and what did you selected ?

**Comment by hyWse** [comment]
I have a german keyboard and i selected de_DE

**Comment by Nurrl** [comment]
That may be your hardware or your software..
