### ISSUE TITLE
keyboard not found 

### ISSUE THREAD

**Issue by mdey0108** [Nurrl/Duckuino#55]
*Short introduction to your problem.*
when we try to compile code give error ketboard not found
__Input code:__
```vb
REM The code your entered in the input text area
```

__Output code:__
```arduino
/* The code outputted by the script, 'none' otherwise */
```

__Error:__
```js
/* Any error outputted by the page or the console, 'none' otherwise */
```

**Comment by Nurrl** [comment]
Hi @mdey0108, This is because you need to select `Arduino Leonardo`/`Arduino Nano` as *Board Type* in Arduino IDE.
This won't work with Arduino UNO.
