### ISSUE TITLE
Help? This is weird..

### ISSUE THREAD

**Issue by acujl** [Nurrl/Duckuino#58]
The Problem basicly: http://prntscr.com/ih1o8d

If u don't trust the link..

**Code:** 
#include "Keyboard.h"

void typeKey(int key)
{
  Keyboard.press(key);
  delay(50);
  Keyboard.release(key);
}

void setup()
{
  // Begining the Keyboard stream
  Keyboard.begin();

  // Wait 500ms
  delay(500);

  delay(3000);

  Keyboard.press(KEY_LEFT_GUI);
  Keyboard.press('r');
  Keyboard.releaseAll();

  delay(500);

  Keyboard.print("notepad");

  delay(500);

  typeKey(KEY_RETURN);

  delay(750);

  Keyboard.print("Hello World!!!");

  typeKey(KEY_RETURN);

  // Ending stream
  Keyboard.end();
}

/* Unused endless loop */
void loop() {}

**Problem:**

exit status 1
'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

**Comment by Nurrl** [comment]
Hi @acujl, to me it looks like you're trying to upload this code on an unsuported board..
On what type of Arduino(or Clone) are you trying to make this work with ?

**Comment by acujl** [comment]
Yes, (well probably a clone yeah) it's a Pro Micro. With a processor Atmel MEGA32U4 as requested to "transform" the arduino into a bad usb (?)

Well I already have the CH341SER driver installed, I don't know what's wrong.. But I guess that the computer doesn't even detects it
![28308388_1849676971733861_1594807629_n](https://user-images.githubusercontent.com/30632902/36448229-d29f0460-167e-11e8-8ab1-661585fde4a8.jpg)

**Comment by Nurrl** [comment]
It should be good to go, but in the tools tab of the Arduino IDE, please make sure that "Arduino Pro Micro" is selected, then you'll be able to compile the Sketch !

**Comment by Nurrl** [comment]
Did it worked ? @acujl

**Comment by acujl** [comment]
My PC isn't able to detect it for some reason :/ any thoughts on that? Or do you know other way to program it? I have uno too!

**Comment by acujl** [comment]
Well problem solved, just changed the cable :V 
Sorry for the inconvenience! 

P.S: Showed up as Leonardo but worked just fine!

**Comment by Nurrl** [comment]
No problem @acujl, most of the Chinese cables are charge-only, I did thought about that :v
