### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by northboys** [Nurrl/Duckuino#66]
[[*Short]([url](](url
![capture](https://user-images.githubusercontent.com/38155944/39403998-8a3a79a6-4bb3-11e8-9a13-a87c709737b4.PNG)
)

)) introduction to your problem.*

__Input code:__
```vb
REM The code your entered in the input text area
```

__Output code:__
```arduino
/* The code outputted by the script, 'none' otherwise */
```

__Error:__
```js
/* Any error outputted by the page or the console, 'none' otherwise */
```

**Comment by Plazmaz** [comment]
Hi, as @Nurrl stated, your version is out of date. Please also make sure you fill out the issue fields properly. It makes it much easier for us to debug the issue.
