### ISSUE TITLE
Unable to download sketch (MacOSX)

### ISSUE THREAD

**Issue by DoebelnAtz** [Nurrl/Duckuino#69]
Using a 2013 macbook air (10.12.3) i am unable to download my sketch on Chrome, Safari or Firefox, both Chrome and Firefox give me an unresponsive download window (can't input locale) and Safari fails to download.

**Comment by Nurrl** [comment]
Hi @DoebelnAtz, what are the versions of the those softwares and are you using the latest, live version of Duckuino ?

**Comment by DoebelnAtz** [comment]
I'm using the latest version of all those browsers and the live version of Dckuino

**Comment by Nurrl** [comment]
And what does the page do ? Do you have any error popup or nothing happens ?
