### ISSUE TITLE
CTRL-SHIFT

### ISSUE THREAD

**Issue by bdstr** [Nurrl/Duckuino#71]
*Short introduction to your problem.*

__Input code:__
```vb
CTRL-SHIFT ENTER
```

__Output code:__
```arduino
none
```

__Error:__
```js
⚠ - Error: Unknown command or key 'CTRL-SHIFT' at line: 7.
```

**Comment by Nurrl** [comment]
Hi @bdstr, `CTRL-SHIFT` is an invalid keyword, try `CTRL SHIFT` instead.
Tell me if it resolved it !

**Comment by bdstr** [comment]
Yes, of course it worked now! The problem is with payloads from the list linked on the Duckuino live page.
Thanks for helping!
