### ISSUE TITLE
wrong key

### ISSUE THREAD

**Issue by grawish** [Nurrl/Duckuino#74]
*Short introduction to your problem.*

__Input code:__
```vb
REM The code your entered in the input text area
```

__Output code:__
```arduino
/* The code outputted by the script, 'none' otherwise */
```

__Error:__
```js
/* Any error outputted by the page or the console, 'none' otherwise */
```
please change KEY_LEFT_ESC to KEY_ESC as the esc key is assigned as KEY_ESC in Arduino library
thank you
regards Grawish

**Comment by Nurrl** [comment]
I'm just tired of fucking peoples who don't use the FUCKING TEMPLATE FUCKING CUNT, AND WHO DON'T JUST CHECK IF THEIR ISSUE IS REALLY A FUCKING ISSUE. THIS FUCKING CHANGE HAS BEEN MADE A FUCKING YEAR AGO. JUST TRY FUCKING THINGS BEFORE BEFORE FILLING A FUCKING ISSUE BRO.
Regards, Nurrl.
