### ISSUE TITLE
Error  #include "HID.h"

### ISSUE THREAD

**Issue by juanjosezg** [Nurrl/Duckuino#79]
I got

```
exit status 1
HID.h: No such file or directory
```

I am using Arduino 1.8.7

**Comment by MatteoCollica** [comment]
Same problem, how can I solve?

**Comment by Nurrl** [comment]
Hello, can you describe a bit more the issue, what did you used on Duckuino, with what board are you trying work...
Thanks.

**Comment by Nurrl** [comment]
Hello, I'll close this since it's not active and we have no answer :)
