### ISSUE TITLE
pt_PT locale not working

### ISSUE THREAD

**Issue by imnotender** [Nurrl/Duckuino#80]
Hi, I've been trying to get the pt_PT locale working on my Arduino Micro(the real deal). I've been successful in changing my Keyboard.cpp before, and it worked well for everything I tried, but I had to format my pc last month( first time in the 5 years I've had this PC) and now I can't get it working again, not even by downloading the sketch.

__Input code:__
```vb
STRING pãoxxx
```

__Output code:__
```arduino
/**
 * Made with Duckuino, an open-source project.
 * Check the license at 'https://github.com/Nurrl/Duckuino/blob/master/LICENSE'
 */

#include "Keyboard.h"

void typeKey(uint8_t key)
{
  Keyboard.press(key);
  delay(50);
  Keyboard.release(key);
}

/* Init function */
void setup()
{
  // Begining the Keyboard stream
  Keyboard.begin();

  // Wait 500ms
  delay(500);

  Keyboard.print(F("pãoxxx"));

  // Ending stream
  Keyboard.end();
}

/* Unused endless loop */
void loop() {}
```

__Error:__
```js
none
```
The above code, which should print pãoxxx, just outputs pxoxxx. I even tried downgrading the IDE, using the LocaleKeyboard.js repo and the LocaleKeyboard.bat/.sh, but nothing seems to work.
Using latest version Win10.

**Comment by Nurrl** [comment]
Hello, unfortunately, the default Arduino/Genuino HID Library is only supporting standard Ascii, not Extended Ascii, which means that your `ã` is not in the Duckuino's operating range.

![ASCII](http://www.asciitable.com/index/asciifull.gif)
