### ISSUE TITLE
Upload layout IDE ARDUINO

### ISSUE THREAD

**Issue by stephanodesouza** [Nurrl/Duckuino#86]
I would be able to teach, for lay users like me, how to connect Cidus Whid in the Arduino IDE, to change the layout of the keyboard. In your tutorial teaches you to only modify the Keyborad.cpp file, but does not talk about how to upload the modicication through the IDE. Thank you - By Google Translate pt-BR > Eng

**Comment by Nurrl** [comment]
The locales are not integrated to the Arduino IDE, they are bundled into the .zip you download.
Did I answered your question ?

**Comment by stephanodesouza** [comment]
Te a, thank you
