### ISSUE TITLE
1

### ISSUE THREAD

**Issue by TheMaxMur** [Nurrl/Duckuino#90]
*Short introduction to your problem.*

__Input code:__
```vb
REM The code your entered in the input text area
```

__Output code:__
```arduino
/* The code outputted by the script, 'none' otherwise */
```

__Error:__
```js
/* Any error outputted by the page or the console, 'none' otherwise */
```

**Comment by Plazmaz** [comment]
Please provide actionable or meaningful information when submitting issues. This issue appears to be empty or have no changes from the issue template.
