### ISSUE TITLE
GUI r doesn't open GUI r

### ISSUE THREAD

**Issue by MBR07** [Nurrl/Duckuino#93]
## I. Describe your environment

- Platform:
Desktop
- OS:
Win10x64

## II. Describe your problem

**How to reproduce the bug**
1. Get an Arduino Pro Micro
2. Type "GUI r" in duckuino
3. Keyboard.press("r"); (It is supposed to output Keyboard.press('r');  )

**Observed behavior**
When trying to avhieve GUI r the program outputs the "wrong apostrophe" making the key not push.

**Expected behavior**
GUI r presses GUI + R

**Comment by Nurrl** [comment]
Hello @MBR07, this is fixed in the new version, I'm still working on it ! But you can switch to branch `v2.1` and use it !

**Comment by Nurrl** [comment]
Update: I merged v2.1 into master, you could just use the live version now !

**Comment by MBR07** [comment]
Merci!
