### ISSUE TITLE
page not appear

### ISSUE THREAD

**Issue by him393** [Nurrl/Duckuino#94]
Are you using the live version that could be found [here](https://nurrl.github.io/Duckuino/) ?
  - [ ] Yes, absolutely
  - [ ] No, I might try it out

What type of issue is it ?
  - [ ] Graphical issue (UX, UI, Graphical Glitch)
  - [ ] Feature issue (Command not/bad implemented, Non functionnal feature)
  - [ ] Crash (The buttons clicks does nothing at all, Error in console)
  - [ ] Question (Any type about the project :D)

```
Here are relevant errors/infos outputed by the code !
```

_Describe your problem here :D_

**Comment by Nurrl** [comment]
Hello, please be more specific and fill the issue correctly.
