### ISSUE TITLE
first compile

### ISSUE THREAD

**Issue by oligarhrich** [Nurrl/Duckuino#97]
Are you using the live version that could be found [here](https://nurrl.github.io/Duckuino/) ?
  - [ ] Yes, absolutely
  - [x] No, I might try it out

What type of issue is it ?
  - [ ] Graphical issue (UX, UI, Graphical Glitch)
  - [ ] Feature issue (Command not/bad implemented, Non functionnal feature)
  - [ ] Crash (The buttons clicks does nothing at all, Error in console)
  - [x] Question (Any type about the project :D)

```
Here are relevant errors/infos outputed by the code !
```

_Describe your problem here :D_

**Comment by oligarhrich** [comment]
thanks

**Comment by Nurrl** [comment]
Hey, please ask your question :)
